<?php 
    $data = $block->getAllUsersData();
    $countries = $block->getCountries();
    $currentProductId = $block->getCurrentProductId();
    $currentProductName = $block->getCurrentProductName();
    $currentProductSku = $block->getCurrentProductSku();
    $loggedInUser = $block->getLoggedUserDetails();
    $comments = array_reverse($block->getComments());
?>

<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('#scrollButton').on('click', function() {
                // Scroll to the target element
                $('html, body').animate({
                    scrollTop: $('#comment-form').offset().top
                }, 1000); // Adjust scroll speed if needed
            });
        });
    });
</script>

<button id="scrollButton" class="action submit primary" style="float: right; margin-top:-5px;">Scroll to Form</button>
<?php if (count($comments)): ?>
    <div class="block review-list" id="customer-reviews">
        <?php if (!$block->getHideTitle()): ?>
            <div class="block-title">
                <strong><?= $escaper->escapeHtml(__('Customer Comments')) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <div class="toolbar review-toolbar">
                <?= $block->getChildHtml('toolbar') ?>
            </div>
            <ol class="items review-items">
                <?php foreach ($comments as $_review): ?>
                        <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                            
                       
                            <div class="review-title">
                                        <?= $escaper->escapeHtml($_review['comments']) ?>
                            </div>
                                    
                            <div class="review-details">
                                    <p class="review-author">
                                        <span class="review-details">
                                        <strong> <?= $escaper->escapeHtml(__('Comment by: ')) ?></strong>
                                        </span>
                                        <strong class="review-details-value" itemprop="author">
                                            <?= $escaper->escapeHtml($_review['name']) ?>
                                        </strong>                                        
                                    </p>       
                            </div>

                            <div class="review-details">
                                    <p class="review-author">
                                        <span class="review-details">
                                        <strong> <?= $escaper->escapeHtml(__('Posted On:')) ?></strong>
                                        </span>
                                        <strong class="review-details-value" itemprop="author">
                                            <?= $escaper->escapeHtml($_review['created_at']) ?> 
                                        </strong>
                                    </p>       
                            </div>

                    <?php endforeach; ?>  
            </ol>
            <div class="toolbar review-toolbar">
                <?= $block->getChildHtml('toolbar') ?>
            </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if (empty($comments)): ?>
        <span class="review-title">
            <?= $escaper->escapeHtml(__('No Comments Found...')) ?>
        </span>
        <br><hr><br>
    <?php endif; ?>


<form action="<?= $block->getUrl('orderbook/customer/saveproductdetails') ?>" id="comment-form" method="POST">

    <fieldset class="fieldset">
    <legend class="review-form review-fieldset legend review-legend"><span><?= $block->escapeHtml(__("You're reviewing:")) ?></span><strong><?= $currentProductName; ?></strong></legend><br/>

        <div class="field name required" id="namefield">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name"
                       id="name"
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                       placeholder = "Enter Name Here..."
                       value = "<?= isset($loggedInUser['name']) ?  $loggedInUser['name'] : null ?>"
                       class = "input-text"
                       type="text"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       placeholder="Enter Email Here..."
                       class = "input-text"
                       type = "text"
                       value = "<?= isset($loggedInUser['email']) ?  $loggedInUser['email'] : null ?>"
                       data-validate="{'validate-custom-mob-email-rule':true}" required
                />
            </div>
        </div>

        <div class="field address">
            <label class="label" for="address"><span><?= $block->escapeHtml(__('Address')) ?></span></label>
            <div class="control">
                <input name="address"
                       id="address"
                       title="<?= $block->escapeHtmlAttr(__('Address')) ?>"
                       placeholder="Enter Address Here..."
                       class="input-text"
                       type="text"
                       data-validate="{required:true}"
                />
            </div>
        </div>

        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="phone"
                       id="phone"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       placeholder="Enter Phone Here..."
                       class="input-text"
                       type="number" />
            </div>
        </div>

        <div class="field birthdate required">
            <label><span><?= $block->escapeHtml(__('Select Your Birthdate:')) ?></span>
            <div class="control">
                <input name="birthdate"
                       id="birthdate"
                       title="<?= $block->escapeHtmlAttr(__('Birthdate')) ?>"
                       placeholder="Select Your Birthdate..."
                       class="input-text"
                       type="date"/>
            </div>
        </div></label>

        <div class="field gender">
            <label class="label" for="gender"><span><?= $block->escapeHtml(__('Gender')) ?></span></label>
            <br>
            <label>
            <div class="control">
                <input name="gender"
                       id="male"
                       title="<?= $block->escapeHtmlAttr(__('Male')) ?>"
                       value="Male"
                       class="input-text"
                       type="radio" />
                       <span><?= $block->escapeHtml(__('Male')) ?></span></label>

                <label>
                <input name="gender"
                       id="female"
                       title="<?= $block->escapeHtmlAttr(__('Female')) ?>"
                       value="Female"
                       class="input-text"
                       type="radio" />
                       <span><?= $block->escapeHtml(__('Female')) ?></span></label>
            </div>
        </div>

        <div class="field course">
            <label class="label" for="course"><span><?= $block->escapeHtml(__('Course Books')) ?></span></label>
            <BR>
            <label>
            <div class="control">
                <input name="courses[]"
                       id="course1"
                       title="<?= $block->escapeHtmlAttr(__('Math')) ?>"
                       value="Math"
                       class="input-text"
                       type="checkbox" />
                       <span><?= $block->escapeHtml(__('Math')) ?></span></label>
                       
                <label>       
                <input name="courses[]"
                       id="course2"
                       title="<?= $block->escapeHtmlAttr(__('Science')) ?>"
                       value="Science"
                       class="input-text"
                       type="checkbox" />
                       <span><?= $block->escapeHtml(__('Science')) ?></span></label>
                 
               
               <label><input name="courses[]"
                       id="course3"
                       title="<?= $block->escapeHtmlAttr(__('History')) ?>"
                       value="History"
                       class="input-text"
                       type="checkbox" />
                       <span><?= $block->escapeHtml(__('History')) ?></span></label>
                
                <label>
                <input name="courses[]"
                       id="course4"
                       title="<?= $block->escapeHtmlAttr(__('CS')) ?>"
                       value="CS"
                       class="input-text"
                       type="checkbox" />
                       <span><?= $block->escapeHtml(__('CS')) ?></span></label>
               
            </div>
        </div>

        <div class="field country">
            <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <select name="country"
                       id="country"
                       title="country"
                       class="input-text"
                        >
                        <option value="" disabled class="input-text" selected>Select your country</option>
                        <?php foreach ($countries as $key => $country) : ?> 
                            <?php if ($country !== null) : ?>
                                <option value="<?php echo $country; ?>" class="input-text"><?php echo $country; ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>

               </select>
            </div>
        </div>

        <div class="field professions">
            <label class="label" for="professions"><span><?= $block->escapeHtml(__('Select Professions')) ?></span></label>
            <div class="control">
                <select name="profession[]"
                       id="profession"
                       title="profession"
                       class="input-text"
                        multiple >
                        <option value="" disabled class="input-text" selected>Select Professions</option>
                        <option value="Frontend Developer" class="input-text">Frontend Developer</option>
                        <option value="Backend Developer" class="input-text">Backend Developer</option>
                        <option value="Full Stack Developer" class="input-text">Full Stack Developer</option>
                        <option value="Tester" class="input-text">Tester</option>
                        <option value="Support" class="input-text">Support</option>
                        <option value="HR" class="input-text">HR</option>
               </select>
            </div>
        </div>

        <div class="field comments">
            <label class="label" for="comments"><span><?= $block->escapeHtml(__('Comments')) ?></span></label>
            <div class="control">
                <textarea name="comments"
                       id="comments"
                       title="<?= $block->escapeHtmlAttr(__('Comments')) ?>"
                       placeholder="Enter Comment Here..."
                       class="input-text"
                       type="textarea"
                       data-validate="{required:true}"
                ></textarea>
            </div>
        </div>

        <div class="field product_id">
            <div class="control">
                <input name="product_id"
                       id="product_id"
                       title="<?= $block->escapeHtmlAttr(__('product_id')) ?>"
                       placeholder="Enter Comment Here..."
                       class="input-text"
                       value = <?=  $currentProductId ?>
                       type="hidden"
                       data-validate="{required:true}"
                />
            </div>
        </div>

        <div class="field product_name">
            <div class="control">
                <input name="product_name"
                       id="product_name"
                       title="<?= $block->escapeHtmlAttr(__('product_name')) ?>"
                       class="input-text"
                       value = <?= $currentProductName ?>
                       type="hidden"
                       data-validate="{required:true}"
                />
            </div>
        </div>

        <div class="field product_sku">
            <div class="control">
                <input name="product_sku"
                       id="product_sku"
                       title="<?= $block->escapeHtmlAttr(__('product_sku')) ?>"
                       class="input-text"
                       value = <?=  $currentProductSku ?>
                       type="hidden"
                       data-validate="{required:true}"
                />
            </div>
        </div>
 
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>


</form>

<script>
    const inputDate = document.getElementById("birthdate");
    inputDate.addEventListener("focus",function (evt) {
    if (this.getAttribute("type")==="date") {
        this.showPicker();
    }
    });
</script>